### ISSUE TITLE
subtree not response with error when the OID not exists

### ISSUE THREAD

**Issue by cesarmacias** [markabrahams/node-net-snmp#102]
Hi,

If use subtree with OID that not exist in the device, doneCb is called without error like a normal response. That's make a empty answer, the correct is doneCb wuth error to manage this response.

Consult by snmpwalk:

-bash-4.2$ snmpwalk -v 2c -c public 10.36.236.51  -On .1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22
.1.3.6.1.4.1.4115.1.20.1.1.3.42.1.22 = No Such Instance currently exists at this OID
-bash-4.2$

**Comment by markabrahams** [comment]
Hi @cesarmacias - Net-SNMP's snmpwalk and node-net-snmp's subtree are not SNMP protocol directives, so their implementation and error handling is not governed by RFC standards, nor are they designed to be analogous.

The behaviour of Net-SNMP's snmpwalk is to use sequential GetNext PDUs to find values "under" the given OID.  If no OIDs are found "under" the given OID, it then issues a Get PDU on the OID.  If this doesn't exist, the agent returns an error code of "No Error" and a varbind with Object Type "No Such Instance".  As such, this is not an "error" as defined by the SNMP protocol, as "No Such Instance" and "No Such Object" are special SNMP object types, not SNMP errors.

The behaviour of node-net-snmp's subtree it to use sequential GetNext PDUs for SNMPv1, or GetBulk PDUs for v2c and v3, and returns varbinds "under" the given OID.  If no OIDs are found "under" the given OID, the doneCb is called with a null error object.

Although the node-net-snmp has the freedom to pass an error to doneCb for whatever condition it wants, it seems to align more with the definition of SNMP errors to *not* represent "No Such Instance" and "No Such Object" conditions as error objects to doneCb.  This being the case, what then would be the best thing to return?  I'm not convinced there's strong case to change the current behaviour i.e. no calling of feedCb - as there are no varbinds returned in the subtree scope - and calling doneCb with a null error, indicating there are no errors in the operating of the SNMP protocols and message processing.

You on the other hand - as the writer of client code - know what this condition means (i.e. no varbinds in the subtree scope), and can act accordingly.  In fact, since this is what current library users are expecting, changing this behaviour may well be a breaking change for current library uses, which again steers towards keeping the behaviour here as it currently is.

**Comment by markabrahams** [comment]
No further discussion or suggested improvement on:
https://github.com/markabrahams/node-net-snmp/issues/102#issuecomment-660118941

Closing.
