### ISSUE TITLE
 Integer too long '129' 

### ISSUE THREAD

**Issue by ponikrf** [markabrahams/node-net-snmp#136]
Hi, I got the same problem as [here](https://github.com/markabrahams/node-net-snmp/issues/5) . But I can't fix it with the hack that person used, because after I get another error

```
ResponseInvalidError: OID '1.3.6.1.4.1.40418.2.2.3.3' in request at positiion '0' does not match OID '1.3.6.1.4.1.40418.2.2.3.3.0' in response at position '0'
    at Req.feedCb (/Volumes/WORK/vrack/devices/snmp/node_modules/net-snmp/index.js:1731:22)
    at Req.Session.onSimpleGetResponse [as onResponse] (/Volumes/WORK/vrack/devices/snmp/node_modules/net-snmp/index.js:2089:7)
    at Session.onMsg (/Volumes/WORK/vrack/devices/snmp/node_modules/net-snmp/index.js:2064:7)
    at Socket.emit (events.js:314:20)
    at UDP.onMessage [as onmessage] (dgram.js:919:8)
```
I get a perfectly normal response from snmpget

```
root@ario:/etc/grafana# snmpget -v1 -c public 172.16.101.5 1.3.6.1.4.1.40418.2.2.3.3
iso.3.6.1.4.1.40418.2.2.3.3.0 = INTEGER: 0
```

Here is the code I am using
```js
      var options = {
        version: snmp.Version1
      }
      var session = snmp.createSession('172.16.101.5', 'public', options)
      var oids = ['1.3.6.1.4.1.40418.2.2.3.3']
      session.get(oids, function (error, varbinds) {
        if (error) {
          console.error(error)
        } else {

        }
        session.close()
      })
```

Here is the hack that person used
```js
var length, mayBeLength = buffer.readByte();
if (mayBeLength === 129) {
        var length = buffer.readByte ();
} else {
	var length = mayBeLength;
}
```

**Comment by markabrahams** [comment]
Hi @ponikrf - there is a bug in your code that needs fixing.  The oids array should be ['1.3.6.1.4.1.40418.2.2.3.3.0'], not ['1.3.6.1.4.1.40418.2.2.3.3'].

**Comment by ponikrf** [comment]
> The oids array should be ['1.3.6.1.4.1.40418.2.2.3.3.0'], not ['1.3.6.1.4.1.40418.2.2.3.3'].

Applying a hack it really works. If the hack is not applied I get the same error (Integer too long '129')

Binary data request `snmpget -v1 -c public 172.16.101.5 1.3.6.1.4.1.40418.2.2.3.3.0`
```
0000   f8 e9 82 22 01 f7 7c b2 7d 1f 8d 3f 08 00 45 00
0010   00 4c 79 51 00 00 80 11 00 00 ac 10 65 08 ac 10
0020   65 05 c7 5e 00 a1 00 38 22 78 30 2e 02 01 00 04
0030   06 70 75 62 6c 69 63 a0 21 02 04 6e 44 0b 01 02
0040   01 00 02 01 00 30 13 30 11 06 0d 2b 06 01 04 01
0050   82 bb 62 02 02 03 03 00 05 00
```

Binary data response `iso.3.6.1.4.1.40418.2.2.3.3.0 = INTEGER: 0`
```
0000   7c b2 7d 1f 8d 3f f8 e9 82 22 01 f7 08 00 45 00
0010   00 56 79 51 40 00 ff 11 e0 16 ac 10 65 05 ac 10
0020   65 08 00 a1 c7 5e 00 42 6e 4b 30 82 00 36 02 01
0030   00 04 06 70 75 62 6c 69 63 a2 82 00 27 02 04 6e
0040   44 0b 01 02 01 00 02 01 00 30 82 00 17 30 82 00
0050   13 06 0d 2b 06 01 04 01 82 bb 62 02 02 03 03 00
0060   02 81 01 00
```

Maybe somehow add the permission of this hack to the options officially?

**Comment by markabrahams** [comment]
Thanks for the data @ponikrf - that exposes the problem.

The problem was the lack of support for BER long-form length encoding when reading integers (ITU-T X.609, Section 8.1.3.5 if you're having trouble sleeping).  That encoding is not necessary for the 4-byte integer types used in SNMP, and as such is rarely used in practice.  But your device chose to use it for some reason, and only for the encoding of its final integer (the last four bytes in the response: 02 81 01 00).  It's completely within standard, just rare.  Most devices would stick with the short-form encoding instead i.e. 02 01 00.

I've added a fix for this according to the ASN.1 BER long-form length encoding rules (no hack required!) and published the fix in version 2.9.8 of the npm.

I don't have a device that does long-form length encoding, so this code hasn't been tested against a real device.  If you're able to test the new version and let me know if it fixes your problem, that would be great.

**Comment by ponikrf** [comment]
I reinstalled and checked - everything works as it should. Thank you very much for the work you have done.

**Comment by markabrahams** [comment]
No problems - thanks for confirming!
