### ISSUE TITLE
Deleting user alone in the forwarder proxy

### ISSUE THREAD

**Issue by Sandy1701** [markabrahams/node-net-snmp#215]
1. I need to delete the user in proxy forwarder is there any way to do it without deleting the entire context.? 
2. And also can we add multiple user to the same context in the proxy forwarder.

**Comment by markabrahams** [comment]
Hi @Sandy1701 - on these:

1. No there isn't.  Deleting a user in the proxy forwarder would have the effect of disabling the entire proxy, as there is no way for user authentication on the remote target to succeed.  This produces the same effective result as deleting the entire proxy (i.e. the proxy no longer works) - which is the supported method of disabling the proxy.  So just delete the proxy to achieve that result.
2. No you can't - there is a one-to-one relationship between a proxy's context and the user in the proxy.  Or, in other words, a context selects exactly one target (technically transport/target/port combination), and selects exactly one user for authentication on that target.  This is intentional, to avoid having to introduce an additional user-selection mechanism that would add unnecessary and unwanted complexity to the design.
