### ISSUE TITLE
MIB parser and MIB module store

### ISSUE THREAD

**Issue by markabrahams** [markabrahams/node-net-snmp#58]
npm release v2.3.0 implements a MIB parser and a MIB module store, created by new API call:

```
var store = snmp.createModuleStore ();
```

The idea is to parse MIB files into the "module store", where MIB module definitions are stored/retrieved as JSON objects.  Also includes a one-liner to register the parsed MIBs for use in your SNMP agent.  In three short commands, you're set up to write out to your agent's MIB:

```
store.loadFromFile ("/path/to/your/mibs/SNMPv2-MIB.mib");
var providers = store.getProvidersForModule ("SNMPv2-MIB");
agent.getMib ().registerProviders (providers);
```

From there, start cranking out your MIB:

```
var mib = agent.getMib ();
mib.setScalarValue ("sysDescr", "The most powerful system you can think of");
mib.setScalarValue ("sysName", "multiplied-by-six");
mib.addTableRow ("sysOREntry", [1, "1.3.6.1.4.1.47491.42.43.44.45", "I've dreamed up this MIB", 20]);
```

Pretty straight-forward.  If you're into that sort of thing.

See the README.md docs for more info.

**Comment by yboujraf** [comment]
Dear @markabrahams 

Thanks for your work.

To be honest with you, we have developed a gateway  where we could connect different devices with different protocols (client as consumer and server as producer)
We extract the Data model into json file then make some transform/ formula  and it works since 6 years now but windows based. now we would like to use nodejs and typescript first by javascript is accepted too.

Now we would like :

- to support snmp as said above as consumer (nms) and producer (as agent with trap) that means the protocol x (proprietary protocol) we would like to generate with our data model (json file) a mib file and use the mib agent to share the data between to different system doesn't understanding each other and vice-versa
- to parse the mib file from a constructor ( as agent) understanding only snmp to converted in a mib data model in json file and with our gateway be able to share the data to equipment using proprietary protocol.

We found a repository in github to parse mib files but not anymore supported.

### Parse Mib and converted into json file

It is my use case, to parse a mib and dependencies and converted into json file see : 
https://github.com/PrimeEuler/asn2json/issues/2

I found few days ago somebody doing what I need but not support :-(

**My big issue in his code was :**

### Manually I need :

- to identify each mib dependencies I need to parse to extract the data model of  the constructor by changing manually into the code source :-(
- to read first the **imports section** from the constructor
- to verify if all the dependencies are available into the folder if not to advertise missing dependencies or to log into a file eroor parsing file
- then parse each dependency mib file in a dedicated order before to parse the constructor mib file and then generate the json file.

=> I need the way to define a folder where I could add all the dependencies mib file and constructor mib files then proceed for the parse.

### check if index are incorrect for enumeration for example and create an error message at line :

It happen in the mib file that in an enumeration to index has the same value. That's forbiden then as described above to og in a file with the exception with the line and the file ;-)

To be sure you have understood my poor english from Belgium guy ;-) with screenshot.


### This is a copy of the issue but just to understand my issue.

Finally, I used : https://github.com/PrimeEuler/mib.js

### Topic  mib.js

[mib.zip](https://github.com/PrimeEuler/asn2json/files/3948052/mib.zip)

I modified from line 772 
![image](https://user-images.githubusercontent.com/6151258/70584960-02563c00-1bc3-11ea-9d3c-c14806369739.png)

I suffered because the order of loading modules are very important otherwise error.

=> Is there a way that you automated this ?
1. to define a folder with all Mib and dependencies
2. to parse mib file till find "IMPORTS" and load the import modules till we parsed all.

![image](https://user-images.githubusercontent.com/6151258/70585117-709afe80-1bc3-11ea-8331-bda20479b1d4.png)

3. finally generate the MIB.json ;-)

### Topic New features

Thanks for your work and hope you could add this new features 

- select a folder where all mib and dependencies are , 
- parsing all mib and verify the dependencies 
- check if index are incorrect for enumeration for example and create an error message at line :

![image](https://user-images.githubusercontent.com/6151258/70586918-d047d880-1bc8-11ea-885f-6cb7b9172e54.png)

and then generate the json file ;-)

You have 99.999999999% done

Best Regards
Youssef


### contribution

If you need somebody to test I am here and contribute the community.
I did last month with another repository for other purpose, the guy was very open and finally I spent my time to learn the protocols, to define use cases and I have all the emulators for testing the code. Now we have 92% code coverage and supporting all the protocol. 8% not done is because we don't have emulators or device tests for the use cases but not mandatory.

I am here to contribute not for using your code as it is. I am respecting the community and would like to share my knowledge too.

Best Regards,
Youssef

**Comment by markabrahams** [comment]
I'm remiss not to mention that I lifted the MIB parser from @PrimeEuler - thank you for your fine work on this @PrimeEuler!

In particular I took the one from:
https://github.com/PrimeEuler/nms.js

But afterwards discovered a later version at:
https://github.com/PrimeEuler/asn2json

which I'll probably move node-net-snmp to at some point.  For now the current one is doing the main job OK, which is to parse to a JSON representation that can be transformed to MIB provider definitions to register with an agent's MIB for immediate use.

**Comment by markabrahams** [comment]
@yboujraf - node-net-snmp isn't the owner of the MIB parser, so the right place to make any improvements to this would be in the asn2json project.

(1) On the MIB dependency management issue:
Personally, I don't see a strong use case for a user-defined MIB folder within the node-net-snmp library.  You already have the base SMIv1 and SMIv2 loaded for you.  You, by definition, must have downloaded all of the additional MIB files you want with dependencies, so you've already had to appreciate the MIB dependencies outside the library.  Further, you know the MIB(s) you want to load into the agent, so you know the entry MIB(s), whereas the library would be guessing when enumerating a folder full of MIBs in an arbitrary order.  These all point to doing this MIB dependecy management outside the node-net-snmp library; as such I won't be adding this feature to node-net-snmp.

(2) On the MIB parser checking for enumeration errors issue:
This needs to be handled by the parser in the asn2json project.

Your enthusiasm to help is commendable open source project.  A large help is to read and abide by the CONTRIBUTING.md for a project.  As I've mentioned previously, the guidelines state: (What never to do, point 1): "Please do not raise more than one topic in an issue."

Closing this topic now, as the issue it was raised for - implementing MIB parsing and a MIB module store - is now in place.

**Comment by yboujraf** [comment]
@markabrahams 

Thank you for your answer.

Best Regards,
Yousssef
